# Generated by Django 4.1.4 on 2023-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defaultuser.jpeg', upload_to='profilepics'),
        ),
    ]
