# Generated by Django 4.1.4 on 2023-02-07 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_orderitem_reviews'),
        ('users', '0003_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='orderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.orderitem'),
        ),
    ]
