# Generated by Django 4.1.4 on 2023-02-07 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_remove_orderitem_reviews'),
        ('users', '0004_reviews_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='orderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orderitem'),
        ),
    ]
