# Generated by Django 4.1.4 on 2023-02-07 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_reviews_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='text',
        ),
    ]
