# Generated by Django 4.1.4 on 2023-02-06 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Title',
            new_name='title',
        ),
    ]
