# Generated by Django 4.1.4 on 2023-01-25 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(default='default.jpg', upload_to='products')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductItems',
        ),
        migrations.RenameField(
            model_name='features',
            old_name='name',
            new_name='featuretext',
        ),
    ]
