# Generated by Django 4.1.4 on 2023-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_items_delete_productitems_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100)),
                ('heading2', models.CharField(max_length=100)),
                ('bulletPoint', models.CharField(max_length=100)),
                ('paragraph', models.CharField(max_length=200)),
            ],
        ),
    ]
