# Generated by Django 4.1.4 on 2023-01-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_items_image5'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutitems',
            name='aboutVideo',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
