# Generated by Django 4.1.4 on 2023-02-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_options',
            field=models.CharField(default='None', max_length=10),
            preserve_default=False,
        ),
    ]
