# Generated by Django 4.1.4 on 2023-02-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_order_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(choices=[('DF', 'None'), ('GL', 'goggles'), ('SH', 'Shirts'), ('PN', 'Pants'), ('SK', 'Skirts'), ('SH', 'Shoes')], default='DF', max_length=5),
            preserve_default=False,
        ),
    ]
