# Generated by Django 4.1.4 on 2023-02-04 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_items_likers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='category',
            new_name='category_choices',
        ),
    ]
