# Generated by Django 4.1.4 on 2023-02-04 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_alter_orderitem_size_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='size_choices',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(default='M', max_length=5),
        ),
    ]
