# Generated by Django 4.1.4 on 2023-02-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_reviews'),
        ('shop', '0028_alter_items_category_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='users.reviews'),
        ),
    ]
