# Generated by Django 4.1.4 on 2023-02-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_orderitem_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='reviews',
        ),
    ]
